floydnant/rockket

- client-v2/src/app/app-routing.module.ts
- client-v2/src/app/app.module.ts
- client-v2/src/app/components/templates/sidebar-layout/sidebar-layout.component.html
- client-v2/src/app/components/templates/sidebar-layout/sidebar-layout.component.test.ts
- client-v2/src/app/components/templates/sidebar-layout/sidebar-layout.component.ts
- client-v2/src/app/pages/home/home.component.html
- client-v2/src/app/pages/settings/account/account.component.html
- client-v2/src/app/pages/settings/account/account.component.ts
- client-v2/src/app/pages/settings/appearance/appearance.component.html
- client-v2/src/app/pages/settings/appearance/appearance.component.ts
- client-v2/src/app/pages/settings/general/general.component.html
- client-v2/src/app/pages/settings/general/general.component.ts
- client-v2/src/app/pages/settings/settings.component.html
- client-v2/src/app/pages/settings/settings.component.spec.ts
- client-v2/src/app/pages/settings/settings.component.ts
- client-v2/src/styles.css
Resolves #111 
- Add a new page `/settings`
- Update the `sidebar-layout` component to make resizing disableable
- Update `<a>` styles to not kick in, when used as a button
- Implementing proper breadcrumbs for the settings pages #114
- Protecting the route with a guard #113
> Add settings UI

- client-v2/src/app/app.module.ts
- client-v2/src/styles.css
> Update hot toast styles

- client-v2/src/app/components/organisms/entity-view/entity-view.component.test.ts
- client-v2/src/app/components/organisms/entity-view/views/tasklist-view/tasklist-view.component.test.ts
- client-v2/src/environments/environment-info.ts
> Fix `process is not defined` issue

- check-dependencies-label-for-pr.sh
- netlify.toml
> Skip netlify build for PRs that have the label "dependencies"

- server/src/entities/list/list.repository.ts
- server/src/entities/list/list.service.ts
- server/src/prisma-abstractions/db-helper.ts
- server/test/lists.e2e-spec.ts
Resolves #195 
- Delete lists recursively
- Delete all tasks inside the list and nested ones
- Delete all associated data with the tasks (just like normal task deletion)
> Delete lists recursively

- .github/workflows/create-pr-db.yml
- .github/workflows/tests.yml
- README.md
- check-dependencies-label-for-pr.sh
- client-v2/src/app/pages/landing-page/landing-page.component.html
- client-v2/src/environments/environment-info.ts
- package.json
- server/.vscode/settings.json
- server/get-pull-number-from-branch.sh
- server/package-lock.json
- server/package.json
- Find & Replace 'todo-app' with 'rockket' with few exceptions
- Minor changes to surrounding code
> Update app name to rockket

- client-v2/package-lock.json
- client-v2/package.json
- client-v2/src/app/app.module.ts
- client-v2/src/app/pages/app.component.spec.ts
- client-v2/src/app/pages/app.component.ts
- client-v2/src/app/services/insights.service.spec.ts
- client-v2/src/app/services/insights.service.ts
- client-v2/src/app/utils/unit-test.mocks.ts
- client-v2/src/environments/environment-info.ts
- client-v2/src/environments/environment.prod.ts
- client-v2/src/environments/environment.ts
- server/package-lock.json
- server/package.json
- server/src/app.module.ts
- server/src/config.schema.ts
- server/src/insights.service.ts
- server/src/main.ts
- server/src/shared/errors.model.ts
- Add Azure Application Insights SDKs to both server and client
- Update config schema
> Add Telemetry

- client-v2/src/app/components/organisms/entity-view/views/tasklist-view/tasklist-view.component.html
- client-v2/src/app/components/templates/sidebar-layout/sidebar-layout.component.html
- client-v2/src/app/components/templates/sidebar-layout/sidebar-layout.component.ts
- client-v2/src/app/pages/home/dashboard/dashboard.component.html
- client-v2/src/app/pages/settings/appearance/appearance.component.html
- client-v2/src/app/pages/settings/general/general.component.html
- Add notes to empty looking pages
- Fix children not truncating in `tasklist-view`
- Fix error when sidebar is not resizable
> Add notes to empty pages

- .github/workflows/tests.yml
- client-v2/package-lock.json
- server/.gitignore
- server/package-lock.json
- server/package.json
- server/prisma/backups/pull-snapshot.ts
- server/prisma/backups/push-snapshot.ts
- server/prisma/backups/snapshot.helpers.ts
- server/test/app.e2e-spec.ts
- server/test/testing-utils.ts
- server/tsconfig.json
- Add script for pulling a db snapshot
- Add script for pushing a db snapshot
> feat: implement db backup pull & push scripts

- netlify.toml
- See pr title
-
-   [ ] Package versions incremented according to [semantic versioning](https://semver.org/), `package-lock.json` updated (`npm i`)
-   [ ] Code is sufficiently documented with comments
-   [ ] Docs updated to reflect changes
-   [ ] All code used for temporary testing removed (`console.log()` etc.)
-   [ ] Outstanding todos marked with `@TODO` comments
-   [ ] All commented out code removed
-   [ ] If the schema changed, migrations are generated and tested
-   [ …
> ci: skip nx cache in netlify build

- apps/rockket-web/.eslintrc.json
- apps/rockket-web/src/app/components/atoms/inline-editor/inline-editor.component.html
- apps/rockket-web/src/app/components/molecules/editable-entity-heading/editable-entity-title.component.html
- apps/rockket-web/src/app/components/organisms/task/task.component.html
- apps/rockket-web/src/app/components/templates/sidebar-layout/sidebar-layout.component.html
- apps/rockket-web/src/app/rich-text-editor/tip-tap-editor/tip-tap-editor.component.css
- apps/rockket-web/tailwind.config.js
- fix: fix text overflows in inline- and rt-editor
- feat: don't vertically center entity icons but keep them at the start
- feat: allow sidebar to grow to 70vw, fix resize handle
-
> feat: fix text overflows, small styling enhancements

- apps/rockket-web/src/app/components/atoms/entity-page-label/entity-page-label.component.ts
- apps/rockket-web/src/app/components/atoms/inline-editor/inline-editor.component.html
- apps/rockket-web/src/app/pages/home/home.component.html
- apps/rockket-web/src/app/pages/home/search/search.component.html
> feat: disallow translations for user generated content

- apps/rockket-web/src/app/components/organisms/task-tree/task-tree.component.css
- apps/rockket-web/src/app/components/organisms/task-tree/task-tree.component.html
- apps/rockket-web/src/app/components/organisms/task-tree/task-tree.component.ts
> refactor: rename indent line helpers

- apps/rockket-web/src/app/components/molecules/breadcrumbs/breadcrumbs.component.html
- apps/rockket-web/src/app/components/organisms/entity-view/views/tasklist-view/tasklist-view.component.html
- apps/rockket-web/src/app/pages/home/home.component.html
- apps/rockket-web/src/app/pages/home/home.component.ts
- apps/rockket-web/src/app/tooltip/tooltip.directive.ts
- apps/rockket-web/src/app/tooltip/tooltip/tooltip.component.css
- apps/rockket-web/src/app/tooltip/tooltip/tooltip.component.ts
- Add tooltips to breadcrumbs
- Don't wrap sublists in `tasklist-view` but stack them
-
> feat: improve entity tooltips, dont wrap sublists in tasklist-view

- .github/labeler.yml
- .github/pull_request_template.md
> docs: improve pr template, update labeler to include `commons` package

- apps/rockket-web/src/app/store/entities/task/task.actions.ts
- apps/rockket-web/src/app/store/entities/task/task.effects.ts
- apps/rockket-web/src/app/store/entities/task/task.reducer.ts
- Adds another argument to the task update actions called `listId` which narrows down the amount of tasks to iterate while querying
-
> refactor: minor improvements to the task store

- apps/rockket-backend/prisma/backups/pull-snapshot.ts
> feat: add last migration name to snapshot file name

- apps/rockket-web/src/app/dropdown/drop-down/drop-down.component.html
- apps/rockket-web/src/main.css
- Changes dropdown background & border colors and glass blur
- Changes dropdown menu item highlight color to be more prominent
- Makes the dropdown separators extend to the outer borders of the dropdown menu
-
> feat: improve drop down styles

- apps/rockket-web/src/app/components/organisms/task/task.component.css
- apps/rockket-web/src/app/components/templates/main-pane/main-pane.component.ts
- apps/rockket-web/src/app/components/templates/sidebar-layout/sidebar-layout.component.css
- apps/rockket-web/src/app/pages/home/home.component.css
- apps/rockket-web/src/main.css
- Instead of specifying the complete scrollbar styles, we now use the `scrollbar-color` and `scrollbar-width` properties
- We still resort back to the previous implementation if the above properties are not supported
- Fix issue where the sidebar tree items would jump around when hovered
-
> feat: improve scrollbar styles

- apps/rockket-web/src/app/rich-text-editor/editor-features/copy-as-html.feature.ts
- apps/rockket-web/src/app/rich-text-editor/editor.features.ts
- apps/rockket-web/src/app/rich-text-editor/editor.helpers.ts
- apps/rockket-web/src/app/rich-text-editor/editor.types.ts
- apps/rockket-web/src/app/rich-text-editor/tip-tap-editor-toolbar/tip-tap-editor-toolbar.component.ts
- packages/commons/src/utils/object.utils.ts
> feat: new editor option in non prod envs: copy as html

- apps/rockket-web/src/app/components/organisms/entity-view/views/tasklist-view/tasklist-view.component.html
> feat: new sublist layout

- apps/rockket-web/src/app/components/atoms/entity-page-label/entity-page-label.component.ts
- apps/rockket-web/src/app/components/organisms/entity-view/entity-view.component.html
- apps/rockket-web/src/app/components/organisms/entity-view/views/task-view/task-view.component.html
- apps/rockket-web/src/app/components/organisms/entity-view/views/tasklist-view/tasklist-view.component.html
- apps/rockket-web/src/app/components/organisms/user-menu/user-menu.component.html
- apps/rockket-web/src/app/dropdown/drop-down/drop-down.component.css
- apps/rockket-web/src/app/dropdown/drop-down/drop-down.component.html
- apps/rockket-web/src/app/dropdown/drop-down/drop-down.component.ts
- apps/rockket-web/src/app/pages/settings/settings.component.html
- apps/rockket-web/src/app/shared/entity-menu-items.ts
- apps/rockket-web/src/main.css
- improve naked button and drop down menu item styling
- adjust affected areas
- remove explicit colors from task,tasklist-view buttons
- remove dropdown active route color
-
> feat: improve naked button and drop down menu item styling

- apps/rockket-web/src/app/components/atoms/icons/icon/icons.ts
- apps/rockket-web/src/app/components/atoms/inline-editor/inline-editor.component.html
- apps/rockket-web/src/app/components/molecules/editable-entity-heading/editable-entity-title.component.html
- apps/rockket-web/src/app/components/molecules/editable-entity-heading/editable-entity-title.component.ts
- apps/rockket-web/src/app/components/molecules/page-progress-bar/page-progress-bar.component.html
- apps/rockket-web/src/app/components/molecules/page-progress-bar/page-progress-bar.component.ts
- apps/rockket-web/src/app/components/organisms/entity-view/views/task-view/task-view.component.html
- apps/rockket-web/src/app/components/organisms/entity-view/views/task-view/task-view.component.ts
- apps/rockket-web/src/app/components/organisms/task/task.component.html
- apps/rockket-web/src/app/components/organisms/task/task.component.ts
- apps/rockket-web/src/app/shared/colors.ts
- New discarded color
- Add status button to task view
- New tasklist icon
- Add strikethrough decoration for discarded tasks in task view
-
-   [ ] `Misc` …
> feat: new discarded color

- apps/rockket-web/src/app/components/molecules/breadcrumbs/breadcrumbs.component.html
> fix: full width breadcrumbs in truncation tooltip

- apps/rockket-web/src/app/components/templates/sidebar-layout/sidebar-layout.component.html
- apps/rockket-web/src/app/components/templates/sidebar-layout/sidebar-layout.component.ts
- apps/rockket-web/src/app/resize/resize-handle.component.ts
- apps/rockket-web/src/app/resize/resize.directive.ts
- apps/rockket-web/src/app/shared/defaults.ts
> feat: reset size when resizer clicked

- apps/rockket-web/src/app/components/molecules/entity-description/entity-description.component.html
- apps/rockket-web/src/app/components/molecules/entity-description/entity-description.component.ts
> feat: add option for a boxed editor (disabling naked style)

- apps/rockket-web/src/main.css
- Relates to https://rockket.netlify.app/home/5f2be4d9-4ed5-4bc9-afda-f222f31d8abc
-
> fix: fix icon-btn icon not being centered

- apps/rockket-web/src/app/pages/home/home.component.ts
> feat: remove "keep active entity visible in Explorer" feature

- apps/rockket-web/src/app/components/organisms/entity-view/views/tasklist-view/tasklist-view.component.ts
- apps/rockket-web/src/app/services/entities.service.ts
- apps/rockket-web/src/app/store/entities/entities.reducer.ts
- apps/rockket-web/src/app/store/entities/utils.spec.ts
- apps/rockket-web/src/app/store/entities/utils.ts
- apps/rockket-web/src/app/utils/index.ts
- packages/commons/src/entities.model.ts
Resolves https://rockket.netlify.app/home/68ee45b0-a20f-4977-8346-ff3458e44e1b
-
-   [ ] `Misc` All …
> feat: always sort sublists by `createdAt`

- apps/rockket-web/src/app/pages/home/home.component.html
- apps/rockket-web/src/app/pages/home/home.component.ts
Resolves https://rockket.netlify.app/home/98a6981a-0791-4bf6-b8bf-ec3ce049a459
-
-   [ ] `Misc` All …
> fix: fix explorer loading state

- apps/rockket-web/src/app/components/organisms/task-tree/task-tree.component.ts
Resolves https://rockket.netlify.app/home/3fcf608e-6521-4f6c-bc57-934edb0ac7e9
-
> feat: auto collapse closed tasks

- apps/rockket-web/src/app/app.module.ts
- apps/rockket-web/src/app/components/atoms/icons/icon/icons.ts
- apps/rockket-web/src/app/components/molecules/page-progress-bar/page-progress-bar.component.ts
- apps/rockket-web/src/app/components/organisms/entity-view/shared/sorting/sorting-dropdown.component.html
- apps/rockket-web/src/app/components/organisms/entity-view/shared/sorting/sorting-dropdown.component.spec.ts
- apps/rockket-web/src/app/components/organisms/entity-view/shared/sorting/sorting-dropdown.component.ts
- apps/rockket-web/src/app/components/organisms/entity-view/shared/sorting/task-sorting-strategies.ts
- apps/rockket-web/src/app/components/organisms/entity-view/views/task-view/task-view.component.html
- apps/rockket-web/src/app/components/organisms/entity-view/views/task-view/task-view.component.spec.ts
- apps/rockket-web/src/app/components/organisms/entity-view/views/task-view/task-view.component.ts
- apps/rockket-web/src/app/components/organisms/entity-view/views/tasklist-view/tasklist-view.component.cy.ts
- apps/rockket-web/src/app/components/organisms/entity-view/views/tasklist-view/tasklist-view.component.html
- apps/rockket-web/src/app/components/organisms/entity-view/views/tasklist-view/tasklist-view.component.spec.ts
- apps/rockket-web/src/app/components/organisms/entity-view/views/tasklist-view/tasklist-view.component.ts
- apps/rockket-web/src/app/components/organisms/task-tree/task-tree.component.ts
- apps/rockket-web/src/app/pages/home/home.component.css
- apps/rockket-web/src/app/services/ui-state.service.ts
- apps/rockket-web/src/app/store/entities/utils.ts
- packages/commons/src/task/task-priority.schemas.ts
Resolves https://rockket.netlify.app/home/a4a76fc6-5da6-48bf-9a99-fd372df4269f
-
-   [ ] `Misc` All …
> feat: implement task tree sorting

- apps/rockket-web/src/app/services/entities.service.ts
- packages/commons/src/entities.model.ts
> fix: fix search not properly parsing the request response

- .github/workflows/pr-assign-and-label.yml
> fic(ci): fix labeler action

- .github/dependabot.yml
> feat(ci): batch dependabot updates

- railway.toml
> fix(infra): fix railway predeloy command
